### ISSUE TITLE
Implement MTTR

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pelorus#24]
Two use cases:

1. Automated: Pods go into crash loops and other failures observable from kubernetes
2. Human defined: Some sort of incident ticket getting open or closed. For now we could use GitHub issues to simulate this.

**Comment by jaycoon** [comment]
Thoughts on this?

Automated 1 (failure based): as defined above: check observable failures / unhealthy states
Automated 2 (success based): check observable healthy states / HTTP 200, e.g. use Prometheus health checks to validate recovered state

*May require human definition (per deployment) of healthy state / when to return 200 response, though once declared, is considered automated

**Comment by etsauer** [comment]
@jaycoon yeah, that sounds reasonable, but I think we need to get more specific, and include example commands showing how we'd gather that data. From the above, it looks like "Automated 1" is meant to define the start of the failure, and "Automated 2" is defining end of failure. So let's call it that, and fill in the HOW:

FAILURE START:
```
# Fill in commands to capture
```

FAILURE END:
```
# Fill in commands to capture
```

Would like to hear how @AlyIbrahim is doing this now, as he is actively working this task.

**Comment by etsauer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [How Might We Measure Failure?](https://trello.com/c/6i56yxQ6/5-how-might-we-measure-failure)

**Comment by AlyIbrahim** [comment]
@etsauer @jaycoon 
Currently I am trying to capture when a pod is Deleted/Crashed as the failure start and failure end when the number of pods available are equal to the the requested ones.
Not the most accurate, but I am trying to have a baseline.
More accurate one to me is to use the readiness probe

**Comment by jaycoon** [comment]
@AlyIbrahim @etsauer 
The base case makes sense, and I think this approach is safer, implementing with possible false negatives (e.g. a pod failed, though the Service may still be online because there are other Ready pods). We may even decide not to call this a false negative, but rather a a very good MTTR, and as such could be the target MTTR for the app (i.e. how fast a single pod can restart, maintaining Service availability with no impact to the user).

One thought on this, is to consider Pods and Deployments separately to calculate our MTTR. Right now we are looking a Pod to failure (pod crashed) AND looking to the Deployment config for failure end (desired Replicas). Perhaps we separate **Pod MTTR** and **Deployment MTTR**? Then we can address Pod MTTR as our first phase, and Deployment MTTR as the next phase.

Adding in the readinessProbe will let us be more accurate, as you said. We can also consider a livenessProbe. Both probes will default to Success if not defined, though if defined, we can utilize them in our MTTR definition. Some other thoughts on this for the Pod MTTR:

Base case (BC)
Failure start = Desired state
Failure end = Ready pods reaches desired state

Liveness case (LC)
Failure start = livenessProbe failure
Failure end = livenessProbe success

Readiness case (RC)
Failure start = readinessProbe failure
Failure end = readinessProbe success

The more probes a pod has defined, the more accurate the MTTR will be.
To determine failure start and end, it is likely an AND function: (BC & LC & RC) 
This will detect specific app failures, when the pods may be running and appear fine, for example.
If LC and RC are not defined, they will default to passing, so the function still works with checking only BC.

**Comment by etsauer** [comment]
depends on #35
