### ISSUE TITLE
Explore standing up grafana via the Grafana operator

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pelorus#26]
https://github.com/integr8ly/grafana-operator

**Comment by garethahealy** [comment]
@seravat ; since you've used this @customer recently. Can you give a quick summary of it?

**Comment by seravat** [comment]
So, despite not bringing huge advantages comparing to using the standalone application, I found that being able to provision new dashboards or datasources through the CRDs is indeed good, otherwise you would have to create ConfigMaps and add them as volumes attaching to the /provisioning directory on Grafana - if you want to provision datasources/dashboards on Grafana's startup

It is especially useful if you are doing multiple deployments, for the reasons above.

**Comment by etsauer** [comment]
@garethahealy @seravat yes, that is the specific use case we have here, as currently we are standing up a generic grafana deployment, and then individually "mounting" a dashboard as a CM to grafana, which requires a `patch` of the deployment to add the volume. This is not ideal, as this approach isn't very declarative, so we would like to replace it with the operator & dashboard CRD.

**Comment by ramius345** [comment]
I think I got this working, here is a PR for you to look at.
https://github.com/redhat-cop/pelorus/pull/37
