### ISSUE TITLE
Build a more consumable quickstart/demo that showcases the functionality of the dashboard

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/pelorus#56]
Readme with a walkthrough
Sample app & automation

**Comment by sbailleu** [comment]
Writing script to deploy pipeline containers. Finishing up the script for review. ETA End Of Week

**Comment by kenwilli** [comment]
- [ ] Determine Apps to use for demo, focused on nginx for now
- [ ] Fork their repos from redat-cop and remove promote gates and verify stages (since apps get hung on them sometimes) from pipelines
- [ ] Create a script that will deploy the app, add a change,commit the change then redeploy app
  - [ ] Deploy apps using a script running ansible applier
  - [ ] Add commit messages to html file in niginx and commit
  - [ ] Redeploy the pipeline
